<?php
/**
 * @filefvg 
 * This is the main module file.
 */

/**
 * Implements hook_help().
 */
function holiday_settings_help($path, $arg) 
{

  if ($path == 'admin/help#holiday_settings') 
  {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The holiday_settings module allows the user to add salary details to the Drupal site.') . '</p>';
    return $output;
  }
}

function holiday_settings_menu() {
  $items['holidays'] = array(
    'title' => 'HOLIDAYS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('holiday_settings_form'),
    'access callback' => TRUE,
    );
  return $items;
}

function holiday_settings_form($form,&$form_submit) {


   $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', array('branch')) 
    ->fieldOrderBy('field_branch_name', 'value', 'ASC'); 
    $result = $query->execute();
    
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach($nodes as $node): 
      $branchdata[$node->nid]= $node->field_branch_name[$node->language][0]['value'];
    endforeach;

  $form['branch'] = array(
  '#title' => t('Branch:'),
  '#type' => 'select',
  '#description' => 'Select branch.',
  '#options' => $branchdata,
  //'#default_value' => $dropdown_first,
  '#required' => TRUE,
  );
   
  $form['holidayname'] = array(
    '#title' => t('Name:'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  $form['holidaydetails'] = array(
    '#title' => t('Details:'),
    '#type' => 'textfield',
    '#required' => TRUE,
  );
  $format = 'd-m-Y';
  $form['holidaydate'] = array(
    '#type' => 'date_popup', 
    '#title' => 'Date',
    //'#default_value' => date('c'), //check that out: date in ISO format
     '#date_format' => $format,
     '#date_label_position' => 'within',
     //'#date_timezone' => 'Europe/Rome', 
     //'#date_increment' => 15, 
      '#date_year_range' => '2016:2017', 
 );
 
  $form['submit'] = array(
    '#value' => 'SUBMIT',
    '#attributes' => array('class' => array('mysubmit')),
    '#type' => 'submit',
    );
  return $form;
}

function holiday_settings_form_form_submit($form, &$form_state) {

    //$company = $form_state['values']['company'][$node->nid];
   
    $branch =  $form['branch']['#options'][$form_state['values']['branch']];
    $holidayname = $form_state['values']['holidayname'];
    $holidaydetails = $form_state['values']['holidaydetails'];
    $holidaydate = $form_state['values']['holidaydate'];
  
   
    
    
    $node = new stdClass();
    $node->type = 'holiday_settings';
    //node_object_prepare($node);
    
    $node->uid = '4';
    $node->title    =  $branch;
    $node->language = LANGUAGE_NONE;

    //$node->body[$node->language][0]['value']   = 
    $node->field_branch_holiday[$node->language][0]['value'] =  $branch;
    $node->field_holiday_name[$node->language][0]['value'] =  $holidayname;
    $node->field_holiday_details[$node->language][0]['value']  = $holidaydetails;
    $node->field_holiday_date[$node->language][0]['value']  =  $holidaydate;
   
  
  //$path = 'content/programmatically_created_node_' . date('YmdHis');
  //$node->path = array('alias' => $path);

    node_save($node);
   
  
      if($node){
       drupal_set_message("Holiday details saved successfully");
       //drupal_set_message( $company);
      


      }
     
     
}